//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// User.
    /// </summary>
    // *** Start programmer edit section *** (User CustomAttributes)

    // *** End programmer edit section *** (User CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("UserE", new string[] {
            "Login as \'Login\'",
            "Password as \'Password\'",
            "Email as \'Email\'",
            "Role as \'Role\'"})]
    public class User : ICSSoft.STORMNET.DataObject
    {
        
        private string fLogin;
        
        private string fPassword;
        
        private string fEmail;

        private string fRole;

        // *** Start programmer edit section *** (User CustomMembers)

        // *** End programmer edit section *** (User CustomMembers)


        /// <summary>
        /// Login.
        /// </summary>
        // *** Start programmer edit section *** (User.Login CustomAttributes)

        // *** End programmer edit section *** (User.Login CustomAttributes)
        [StrLen(255)]
        public virtual string Login
        {
            get
            {
                // *** Start programmer edit section *** (User.Login Get start)

                // *** End programmer edit section *** (User.Login Get start)
                string result = this.fLogin;
                // *** Start programmer edit section *** (User.Login Get end)

                // *** End programmer edit section *** (User.Login Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.Login Set start)

                // *** End programmer edit section *** (User.Login Set start)
                this.fLogin = value;
                // *** Start programmer edit section *** (User.Login Set end)

                // *** End programmer edit section *** (User.Login Set end)
            }
        }

        /// <summary>
        /// Password.
        /// </summary>
        // *** Start programmer edit section *** (User.Password CustomAttributes)

        // *** End programmer edit section *** (User.Password CustomAttributes)
        [StrLen(255)]
        public virtual string Password
        {
            get
            {
                // *** Start programmer edit section *** (User.Password Get start)

                // *** End programmer edit section *** (User.Password Get start)
                string result = this.fPassword;
                // *** Start programmer edit section *** (User.Password Get end)

                // *** End programmer edit section *** (User.Password Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.Password Set start)

                // *** End programmer edit section *** (User.Password Set start)
                this.fPassword = value;
                // *** Start programmer edit section *** (User.Password Set end)

                // *** End programmer edit section *** (User.Password Set end)
            }
        }

        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (User.Email CustomAttributes)

        // *** End programmer edit section *** (User.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (User.Email Get start)

                // *** End programmer edit section *** (User.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (User.Email Get end)

                // *** End programmer edit section *** (User.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.Email Set start)

                // *** End programmer edit section *** (User.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (User.Email Set end)

                // *** End programmer edit section *** (User.Email Set end)
            }
        }

        /// <summary>
        /// Role.
        /// </summary>
        // *** Start programmer edit section *** (User.Role CustomAttributes)

        // *** End programmer edit section *** (User.Role CustomAttributes)
        [StrLen(255)]
        public virtual string Role
        {
            get
            {
                // *** Start programmer edit section *** (User.Role Get start)

                // *** End programmer edit section *** (User.Role Get start)
                string result = this.fRole;
                // *** Start programmer edit section *** (User.Role Get end)

                // *** End programmer edit section *** (User.Role Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.Role Set start)

                // *** End programmer edit section *** (User.Role Set start)
                this.fRole = value;
                // *** Start programmer edit section *** (User.Role Set end)

                // *** End programmer edit section *** (User.Role Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "UserE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View UserE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("UserE", typeof(IIS.BookClub.User));
                }
            }
            
            /// <summary>
            /// "UserL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View UserL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("UserL", typeof(IIS.BookClub.User));
                }
            }
        }
    }
}
