//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Встреча клуба.
    /// </summary>
    // *** Start programmer edit section *** (ВстречаКлуба CustomAttributes)

    // *** End programmer edit section *** (ВстречаКлуба CustomAttributes)
    [AutoAltered()]
    [Caption("Встреча клуба")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВстречаКлубаE", new string[] {
            "ДатаВстречи as \'Дата встречи\'"})]
    [AssociatedDetailViewAttribute("ВстречаКлубаE", "Доклад", "ДокладE", true, "", "Доклад", true, new string[] {
            ""})]
    [View("ВстречаКлубаL", new string[] {
            "ДатаВстречи as \'Дата встречи\'"})]
    public class ВстречаКлуба : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВстречи;
        
        private IIS.BookClub.DetailArrayOfДоклад fДоклад;
        
        // *** Start programmer edit section *** (ВстречаКлуба CustomMembers)

        // *** End programmer edit section *** (ВстречаКлуба CustomMembers)

        
        /// <summary>
        /// ДатаВстречи.
        /// </summary>
        // *** Start programmer edit section *** (ВстречаКлуба.ДатаВстречи CustomAttributes)

        // *** End programmer edit section *** (ВстречаКлуба.ДатаВстречи CustomAttributes)
        public virtual System.DateTime ДатаВстречи
        {
            get
            {
                // *** Start programmer edit section *** (ВстречаКлуба.ДатаВстречи Get start)

                // *** End programmer edit section *** (ВстречаКлуба.ДатаВстречи Get start)
                System.DateTime result = this.fДатаВстречи;
                // *** Start programmer edit section *** (ВстречаКлуба.ДатаВстречи Get end)

                // *** End programmer edit section *** (ВстречаКлуба.ДатаВстречи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВстречаКлуба.ДатаВстречи Set start)

                // *** End programmer edit section *** (ВстречаКлуба.ДатаВстречи Set start)
                this.fДатаВстречи = value;
                // *** Start programmer edit section *** (ВстречаКлуба.ДатаВстречи Set end)

                // *** End programmer edit section *** (ВстречаКлуба.ДатаВстречи Set end)
            }
        }
        
        /// <summary>
        /// Встреча клуба.
        /// </summary>
        // *** Start programmer edit section *** (ВстречаКлуба.Доклад CustomAttributes)

        // *** End programmer edit section *** (ВстречаКлуба.Доклад CustomAttributes)
        public virtual IIS.BookClub.DetailArrayOfДоклад Доклад
        {
            get
            {
                // *** Start programmer edit section *** (ВстречаКлуба.Доклад Get start)

                // *** End programmer edit section *** (ВстречаКлуба.Доклад Get start)
                if ((this.fДоклад == null))
                {
                    this.fДоклад = new IIS.BookClub.DetailArrayOfДоклад(this);
                }
                IIS.BookClub.DetailArrayOfДоклад result = this.fДоклад;
                // *** Start programmer edit section *** (ВстречаКлуба.Доклад Get end)

                // *** End programmer edit section *** (ВстречаКлуба.Доклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВстречаКлуба.Доклад Set start)

                // *** End programmer edit section *** (ВстречаКлуба.Доклад Set start)
                this.fДоклад = value;
                // *** Start programmer edit section *** (ВстречаКлуба.Доклад Set end)

                // *** End programmer edit section *** (ВстречаКлуба.Доклад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВстречаКлубаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВстречаКлубаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВстречаКлубаE", typeof(IIS.BookClub.ВстречаКлуба));
                }
            }
            
            /// <summary>
            /// "ВстречаКлубаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВстречаКлубаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВстречаКлубаL", typeof(IIS.BookClub.ВстречаКлуба));
                }
            }
        }
    }
}
