//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Доклад.
    /// </summary>
    // *** Start programmer edit section *** (Доклад CustomAttributes)

    // *** End programmer edit section *** (Доклад CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокладE", new string[] {
            "ДатаДоклада as \'Дата доклада\'",
            "ОценкаКниги as \'Оценка книги\'",
            "URLПрезентации as \'URL презентации\'",
            "URLВидео as \'URL видео\'",
            "Резенция as \'Резенция\'",
            "Книга as \'Книга\'",
            "Книга.Название as \'Название\'",
            "Спикер as \'Спикер\'",
            "Спикер.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Книга.Название",
            "Спикер.Фамилия"})]
    [MasterViewDefineAttribute("ДокладE", "Книга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ДокладE", "Спикер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    public class Доклад : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаДоклада;
        
        private int fОценкаКниги;
        
        private string fURLПрезентации;
        
        private string fURLВидео;
        
        private string fРезенция;
        
        private IIS.BookClub.Книга fКнига;
        
        private IIS.BookClub.Спикер fСпикер;
        
        private IIS.BookClub.ВстречаКлуба fВстречаКлуба;
        
        // *** Start programmer edit section *** (Доклад CustomMembers)

        // *** End programmer edit section *** (Доклад CustomMembers)

        
        /// <summary>
        /// ДатаДоклада.
        /// </summary>
        // *** Start programmer edit section *** (Доклад.ДатаДоклада CustomAttributes)

        // *** End programmer edit section *** (Доклад.ДатаДоклада CustomAttributes)
        public virtual System.DateTime ДатаДоклада
        {
            get
            {
                // *** Start programmer edit section *** (Доклад.ДатаДоклада Get start)

                // *** End programmer edit section *** (Доклад.ДатаДоклада Get start)
                System.DateTime result = this.fДатаДоклада;
                // *** Start programmer edit section *** (Доклад.ДатаДоклада Get end)

                // *** End programmer edit section *** (Доклад.ДатаДоклада Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доклад.ДатаДоклада Set start)

                // *** End programmer edit section *** (Доклад.ДатаДоклада Set start)
                this.fДатаДоклада = value;
                // *** Start programmer edit section *** (Доклад.ДатаДоклада Set end)

                // *** End programmer edit section *** (Доклад.ДатаДоклада Set end)
            }
        }
        
        /// <summary>
        /// ОценкаКниги.
        /// </summary>
        // *** Start programmer edit section *** (Доклад.ОценкаКниги CustomAttributes)

        // *** End programmer edit section *** (Доклад.ОценкаКниги CustomAttributes)
        public virtual int ОценкаКниги
        {
            get
            {
                // *** Start programmer edit section *** (Доклад.ОценкаКниги Get start)

                // *** End programmer edit section *** (Доклад.ОценкаКниги Get start)
                int result = this.fОценкаКниги;
                // *** Start programmer edit section *** (Доклад.ОценкаКниги Get end)

                // *** End programmer edit section *** (Доклад.ОценкаКниги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доклад.ОценкаКниги Set start)

                // *** End programmer edit section *** (Доклад.ОценкаКниги Set start)
                this.fОценкаКниги = value;
                // *** Start programmer edit section *** (Доклад.ОценкаКниги Set end)

                // *** End programmer edit section *** (Доклад.ОценкаКниги Set end)
            }
        }
        
        /// <summary>
        /// URLПрезентации.
        /// </summary>
        // *** Start programmer edit section *** (Доклад.URLПрезентации CustomAttributes)

        // *** End programmer edit section *** (Доклад.URLПрезентации CustomAttributes)
        [StrLen(255)]
        public virtual string URLПрезентации
        {
            get
            {
                // *** Start programmer edit section *** (Доклад.URLПрезентации Get start)

                // *** End programmer edit section *** (Доклад.URLПрезентации Get start)
                string result = this.fURLПрезентации;
                // *** Start programmer edit section *** (Доклад.URLПрезентации Get end)

                // *** End programmer edit section *** (Доклад.URLПрезентации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доклад.URLПрезентации Set start)

                // *** End programmer edit section *** (Доклад.URLПрезентации Set start)
                this.fURLПрезентации = value;
                // *** Start programmer edit section *** (Доклад.URLПрезентации Set end)

                // *** End programmer edit section *** (Доклад.URLПрезентации Set end)
            }
        }
        
        /// <summary>
        /// URLВидео.
        /// </summary>
        // *** Start programmer edit section *** (Доклад.URLВидео CustomAttributes)

        // *** End programmer edit section *** (Доклад.URLВидео CustomAttributes)
        [StrLen(255)]
        public virtual string URLВидео
        {
            get
            {
                // *** Start programmer edit section *** (Доклад.URLВидео Get start)

                // *** End programmer edit section *** (Доклад.URLВидео Get start)
                string result = this.fURLВидео;
                // *** Start programmer edit section *** (Доклад.URLВидео Get end)

                // *** End programmer edit section *** (Доклад.URLВидео Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доклад.URLВидео Set start)

                // *** End programmer edit section *** (Доклад.URLВидео Set start)
                this.fURLВидео = value;
                // *** Start programmer edit section *** (Доклад.URLВидео Set end)

                // *** End programmer edit section *** (Доклад.URLВидео Set end)
            }
        }
        
        /// <summary>
        /// Резенция.
        /// </summary>
        // *** Start programmer edit section *** (Доклад.Резенция CustomAttributes)

        // *** End programmer edit section *** (Доклад.Резенция CustomAttributes)
        [StrLen(255)]
        public virtual string Резенция
        {
            get
            {
                // *** Start programmer edit section *** (Доклад.Резенция Get start)

                // *** End programmer edit section *** (Доклад.Резенция Get start)
                string result = this.fРезенция;
                // *** Start programmer edit section *** (Доклад.Резенция Get end)

                // *** End programmer edit section *** (Доклад.Резенция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доклад.Резенция Set start)

                // *** End programmer edit section *** (Доклад.Резенция Set start)
                this.fРезенция = value;
                // *** Start programmer edit section *** (Доклад.Резенция Set end)

                // *** End programmer edit section *** (Доклад.Резенция Set end)
            }
        }
        
        /// <summary>
        /// Доклад.
        /// </summary>
        // *** Start programmer edit section *** (Доклад.Книга CustomAttributes)

        // *** End programmer edit section *** (Доклад.Книга CustomAttributes)
        [NotNull()]
        public virtual IIS.BookClub.Книга Книга
        {
            get
            {
                // *** Start programmer edit section *** (Доклад.Книга Get start)

                // *** End programmer edit section *** (Доклад.Книга Get start)
                IIS.BookClub.Книга result = this.fКнига;
                // *** Start programmer edit section *** (Доклад.Книга Get end)

                // *** End programmer edit section *** (Доклад.Книга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доклад.Книга Set start)

                // *** End programmer edit section *** (Доклад.Книга Set start)
                this.fКнига = value;
                // *** Start programmer edit section *** (Доклад.Книга Set end)

                // *** End programmer edit section *** (Доклад.Книга Set end)
            }
        }
        
        /// <summary>
        /// Доклад.
        /// </summary>
        // *** Start programmer edit section *** (Доклад.Спикер CustomAttributes)

        // *** End programmer edit section *** (Доклад.Спикер CustomAttributes)
        [NotNull()]
        public virtual IIS.BookClub.Спикер Спикер
        {
            get
            {
                // *** Start programmer edit section *** (Доклад.Спикер Get start)

                // *** End programmer edit section *** (Доклад.Спикер Get start)
                IIS.BookClub.Спикер result = this.fСпикер;
                // *** Start programmer edit section *** (Доклад.Спикер Get end)

                // *** End programmer edit section *** (Доклад.Спикер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доклад.Спикер Set start)

                // *** End programmer edit section *** (Доклад.Спикер Set start)
                this.fСпикер = value;
                // *** Start programmer edit section *** (Доклад.Спикер Set end)

                // *** End programmer edit section *** (Доклад.Спикер Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.BookClub.ВстречаКлуба.
        /// </summary>
        // *** Start programmer edit section *** (Доклад.ВстречаКлуба CustomAttributes)

        // *** End programmer edit section *** (Доклад.ВстречаКлуба CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.BookClub.ВстречаКлуба ВстречаКлуба
        {
            get
            {
                // *** Start programmer edit section *** (Доклад.ВстречаКлуба Get start)

                // *** End programmer edit section *** (Доклад.ВстречаКлуба Get start)
                IIS.BookClub.ВстречаКлуба result = this.fВстречаКлуба;
                // *** Start programmer edit section *** (Доклад.ВстречаКлуба Get end)

                // *** End programmer edit section *** (Доклад.ВстречаКлуба Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доклад.ВстречаКлуба Set start)

                // *** End programmer edit section *** (Доклад.ВстречаКлуба Set start)
                this.fВстречаКлуба = value;
                // *** Start programmer edit section *** (Доклад.ВстречаКлуба Set end)

                // *** End programmer edit section *** (Доклад.ВстречаКлуба Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокладE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокладE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокладE", typeof(IIS.BookClub.Доклад));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Доклад.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfДоклад CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfДоклад CustomAttributes)
    public class DetailArrayOfДоклад : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.BookClub.DetailArrayOfДоклад members)

        // *** End programmer edit section *** (IIS.BookClub.DetailArrayOfДоклад members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Доклад by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Доклад.
        /// </summary>
        public DetailArrayOfДоклад(IIS.BookClub.ВстречаКлуба fВстречаКлуба) : 
                base(typeof(Доклад), ((ICSSoft.STORMNET.DataObject)(fВстречаКлуба)))
        {
        }
        
        public IIS.BookClub.Доклад this[int index]
        {
            get
            {
                return ((IIS.BookClub.Доклад)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.BookClub.Доклад dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
