//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка.
    /// </summary>
    // *** Start programmer edit section *** (Заявка CustomAttributes)

    // *** End programmer edit section *** (Заявка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаE", new string[] {
            "ДатаЗаявки as \'Дата заявки\'",
            "Книга as \'Книга\'",
            "Книга.Название as \'Название\'",
            "Спикер as \'Спикер\'",
            "Спикер.FullName as \'ФИО\'"}, Hidden=new string[] {
            "Книга.Название",
            "Спикер.FullName"})]
    [MasterViewDefineAttribute("ЗаявкаE", "Книга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ЗаявкаE", "Спикер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FullName")]
    [View("ЗаявкаL", new string[] {
            "ДатаЗаявки as \'Дата заявки\'",
            "Книга.Название as \'Название\'",
            "Спикер.FullName as \'ФИО\'"})]
    public class Заявка : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаявки;
        
        private IIS.BookClub.Книга fКнига;
        
        private IIS.BookClub.Спикер fСпикер;
        
        // *** Start programmer edit section *** (Заявка CustomMembers)

        // *** End programmer edit section *** (Заявка CustomMembers)

        
        /// <summary>
        /// ДатаЗаявки.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.ДатаЗаявки CustomAttributes)

        // *** End programmer edit section *** (Заявка.ДатаЗаявки CustomAttributes)
        public virtual System.DateTime ДатаЗаявки
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.ДатаЗаявки Get start)

                // *** End programmer edit section *** (Заявка.ДатаЗаявки Get start)
                System.DateTime result = this.fДатаЗаявки;
                // *** Start programmer edit section *** (Заявка.ДатаЗаявки Get end)

                // *** End programmer edit section *** (Заявка.ДатаЗаявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.ДатаЗаявки Set start)

                // *** End programmer edit section *** (Заявка.ДатаЗаявки Set start)
                this.fДатаЗаявки = value;
                // *** Start programmer edit section *** (Заявка.ДатаЗаявки Set end)

                // *** End programmer edit section *** (Заявка.ДатаЗаявки Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Книга CustomAttributes)

        // *** End programmer edit section *** (Заявка.Книга CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "Книга"})]
        public virtual IIS.BookClub.Книга Книга
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Книга Get start)

                // *** End programmer edit section *** (Заявка.Книга Get start)
                IIS.BookClub.Книга result = this.fКнига;
                // *** Start programmer edit section *** (Заявка.Книга Get end)

                // *** End programmer edit section *** (Заявка.Книга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Книга Set start)

                // *** End programmer edit section *** (Заявка.Книга Set start)
                this.fКнига = value;
                // *** Start programmer edit section *** (Заявка.Книга Set end)

                // *** End programmer edit section *** (Заявка.Книга Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Спикер CustomAttributes)

        // *** End programmer edit section *** (Заявка.Спикер CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "Спикер"})]
        public virtual IIS.BookClub.Спикер Спикер
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Спикер Get start)

                // *** End programmer edit section *** (Заявка.Спикер Get start)
                IIS.BookClub.Спикер result = this.fСпикер;
                // *** Start programmer edit section *** (Заявка.Спикер Get end)

                // *** End programmer edit section *** (Заявка.Спикер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Спикер Set start)

                // *** End programmer edit section *** (Заявка.Спикер Set start)
                this.fСпикер = value;
                // *** Start programmer edit section *** (Заявка.Спикер Set end)

                // *** End programmer edit section *** (Заявка.Спикер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаE", typeof(IIS.BookClub.Заявка));
                }
            }
            
            /// <summary>
            /// "ЗаявкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаL", typeof(IIS.BookClub.Заявка));
                }
            }
        }
    }
}
