//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub
{
    using System;
    using System.Linq;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.FunctionalLanguage;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Книга.
    /// </summary>
    // *** Start programmer edit section *** (Книга CustomAttributes)

    // *** End programmer edit section *** (Книга CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КнигаE", new string[] {
            "Название as \'Название\'",
            "Автор as \'Автор\'",
            "КоличествоСтраниц as \'Количество страниц\'",
            "URLОбложки as \'URL обложки\'",
            "URLОписания as \'URL описания\'",
            "Теги as \'Теги\'",
            "СредняяОценка as \'Средняя оценка\'"})]
    [View("КнигаL", new string[] {
            "Название as \'Название\'",
            "Автор as \'Автор\'",
            "КоличествоСтраниц as \'Количество страниц\'",
            "Теги as \'Теги\'",
            "СредняяОценка as \'Средняя оценка\'"})]
    public class Книга : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fАвтор;
        
        private int fКоличествоСтраниц;
        
        private string fURLОбложки;
        
        private string fURLОписания;
        
        private string fТеги;

        private double fСредняяОценка;
        
        // *** Start programmer edit section *** (Книга CustomMembers)

        // *** End programmer edit section *** (Книга CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Книга.Название CustomAttributes)

        // *** End programmer edit section *** (Книга.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Книга.Название Get start)

                // *** End programmer edit section *** (Книга.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Книга.Название Get end)

                // *** End programmer edit section *** (Книга.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Книга.Название Set start)

                // *** End programmer edit section *** (Книга.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Книга.Название Set end)

                // *** End programmer edit section *** (Книга.Название Set end)
            }
        }
        
        /// <summary>
        /// Автор.
        /// </summary>
        // *** Start programmer edit section *** (Книга.Автор CustomAttributes)

        // *** End programmer edit section *** (Книга.Автор CustomAttributes)
        [StrLen(255)]
        public virtual string Автор
        {
            get
            {
                // *** Start programmer edit section *** (Книга.Автор Get start)

                // *** End programmer edit section *** (Книга.Автор Get start)
                string result = this.fАвтор;
                // *** Start programmer edit section *** (Книга.Автор Get end)

                // *** End programmer edit section *** (Книга.Автор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Книга.Автор Set start)

                // *** End programmer edit section *** (Книга.Автор Set start)
                this.fАвтор = value;
                // *** Start programmer edit section *** (Книга.Автор Set end)

                // *** End programmer edit section *** (Книга.Автор Set end)
            }
        }
        
        /// <summary>
        /// КоличествоСтраниц.
        /// </summary>
        // *** Start programmer edit section *** (Книга.КоличествоСтраниц CustomAttributes)

        // *** End programmer edit section *** (Книга.КоличествоСтраниц CustomAttributes)
        public virtual int КоличествоСтраниц
        {
            get
            {
                // *** Start programmer edit section *** (Книга.КоличествоСтраниц Get start)

                // *** End programmer edit section *** (Книга.КоличествоСтраниц Get start)
                int result = this.fКоличествоСтраниц;
                // *** Start programmer edit section *** (Книга.КоличествоСтраниц Get end)

                // *** End programmer edit section *** (Книга.КоличествоСтраниц Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Книга.КоличествоСтраниц Set start)

                // *** End programmer edit section *** (Книга.КоличествоСтраниц Set start)
                this.fКоличествоСтраниц = value;
                // *** Start programmer edit section *** (Книга.КоличествоСтраниц Set end)

                // *** End programmer edit section *** (Книга.КоличествоСтраниц Set end)
            }
        }
        
        /// <summary>
        /// URLОбложки.
        /// </summary>
        // *** Start programmer edit section *** (Книга.URLОбложки CustomAttributes)

        // *** End programmer edit section *** (Книга.URLОбложки CustomAttributes)
        [StrLen(255)]
        public virtual string URLОбложки
        {
            get
            {
                // *** Start programmer edit section *** (Книга.URLОбложки Get start)

                // *** End programmer edit section *** (Книга.URLОбложки Get start)
                string result = this.fURLОбложки;
                // *** Start programmer edit section *** (Книга.URLОбложки Get end)

                // *** End programmer edit section *** (Книга.URLОбложки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Книга.URLОбложки Set start)

                // *** End programmer edit section *** (Книга.URLОбложки Set start)
                this.fURLОбложки = value;
                // *** Start programmer edit section *** (Книга.URLОбложки Set end)

                // *** End programmer edit section *** (Книга.URLОбложки Set end)
            }
        }
        
        /// <summary>
        /// URLОписания.
        /// </summary>
        // *** Start programmer edit section *** (Книга.URLОписания CustomAttributes)

        // *** End programmer edit section *** (Книга.URLОписания CustomAttributes)
        [StrLen(255)]
        public virtual string URLОписания
        {
            get
            {
                // *** Start programmer edit section *** (Книга.URLОписания Get start)

                // *** End programmer edit section *** (Книга.URLОписания Get start)
                string result = this.fURLОписания;
                // *** Start programmer edit section *** (Книга.URLОписания Get end)

                // *** End programmer edit section *** (Книга.URLОписания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Книга.URLОписания Set start)

                // *** End programmer edit section *** (Книга.URLОписания Set start)
                this.fURLОписания = value;
                // *** Start programmer edit section *** (Книга.URLОписания Set end)

                // *** End programmer edit section *** (Книга.URLОписания Set end)
            }
        }
        
        /// <summary>
        /// Теги.
        /// </summary>
        // *** Start programmer edit section *** (Книга.Теги CustomAttributes)

        // *** End programmer edit section *** (Книга.Теги CustomAttributes)
        [StrLen(255)]
        public virtual string Теги
        {
            get
            {
                // *** Start programmer edit section *** (Книга.Теги Get start)

                // *** End programmer edit section *** (Книга.Теги Get start)
                string result = this.fТеги;
                // *** Start programmer edit section *** (Книга.Теги Get end)

                // *** End programmer edit section *** (Книга.Теги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Книга.Теги Set start)

                // *** End programmer edit section *** (Книга.Теги Set start)
                this.fТеги = value;
                // *** Start programmer edit section *** (Книга.Теги Set end)

                // *** End programmer edit section *** (Книга.Теги Set end)
            }
        }

        /// <summary>
        /// СредняяОценка.
        /// </summary>
        // *** Start programmer edit section *** (Книга.СредняяОценка CustomAttributes)

        // *** End programmer edit section *** (Книга.СредняяОценка CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual double СредняяОценка
        {
            get
            {
                // *** Start programmer edit section *** (Книга.СредняяОценка Get)
                LoadingCustomizationStruct lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(Доклад), Доклад.Views.ДокладE);
                lcs.LimitFunction = FunctionBuilder.BuildEquals<Доклад>(x => x.Книга, this);
                SQLDataService ds = (SQLDataService)DataServiceProvider.DataService;
                var dataObjs = ds.LoadObjects(lcs).Cast<Доклад>().ToList();
                double mark = 0;
                foreach (var obj in dataObjs)
                {
                    mark += obj.ОценкаКниги;
                }
                double result = mark / dataObjs.Count;
                // *** End programmer edit section *** (Книга.СредняяОценка Get)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Книга.СредняяОценка Set)
                // *** End programmer edit section *** (Книга.СредняяОценка Set)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КнигаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КнигаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КнигаE", typeof(IIS.BookClub.Книга));
                }
            }
            
            /// <summary>
            /// "КнигаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КнигаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КнигаL", typeof(IIS.BookClub.Книга));
                }
            }
        }
    }
}
