//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// План встречи.
    /// </summary>
    // *** Start programmer edit section *** (ПланВстречи CustomAttributes)

    // *** End programmer edit section *** (ПланВстречи CustomAttributes)
    [AutoAltered()]
    [Caption("План встречи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПланВстречиE", new string[] {
            "ДатаВстречи as \'Дата встречи\'"})]
    [View("ПланВстречиL", new string[] {
            "ДатаВстречи as \'Дата встречи\'"})]
    public class ПланВстречи : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВстречи;
        
        // *** Start programmer edit section *** (ПланВстречи CustomMembers)

        // *** End programmer edit section *** (ПланВстречи CustomMembers)

        
        /// <summary>
        /// ДатаВстречи.
        /// </summary>
        // *** Start programmer edit section *** (ПланВстречи.ДатаВстречи CustomAttributes)

        // *** End programmer edit section *** (ПланВстречи.ДатаВстречи CustomAttributes)
        public virtual System.DateTime ДатаВстречи
        {
            get
            {
                // *** Start programmer edit section *** (ПланВстречи.ДатаВстречи Get start)

                // *** End programmer edit section *** (ПланВстречи.ДатаВстречи Get start)
                System.DateTime result = this.fДатаВстречи;
                // *** Start programmer edit section *** (ПланВстречи.ДатаВстречи Get end)

                // *** End programmer edit section *** (ПланВстречи.ДатаВстречи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланВстречи.ДатаВстречи Set start)

                // *** End programmer edit section *** (ПланВстречи.ДатаВстречи Set start)
                this.fДатаВстречи = value;
                // *** Start programmer edit section *** (ПланВстречи.ДатаВстречи Set end)

                // *** End programmer edit section *** (ПланВстречи.ДатаВстречи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПланВстречиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланВстречиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланВстречиE", typeof(IIS.BookClub.ПланВстречи));
                }
            }
            
            /// <summary>
            /// "ПланВстречиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланВстречиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланВстречиL", typeof(IIS.BookClub.ПланВстречи));
                }
            }
        }
    }
}
