//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спикер.
    /// </summary>
    // *** Start programmer edit section *** (Спикер CustomAttributes)

    // *** End programmer edit section *** (Спикер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпикерE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "FullName"}, Hidden = new string[] {
            "FullName"})]
    [View("СпикерL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "FullName"}, Hidden = new string[] {
            "FullName"})]
    public class Спикер : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        // *** Start programmer edit section *** (Спикер CustomMembers)

        // *** End programmer edit section *** (Спикер CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Спикер.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Спикер.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Спикер.Фамилия Get start)

                // *** End programmer edit section *** (Спикер.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Спикер.Фамилия Get end)

                // *** End programmer edit section *** (Спикер.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спикер.Фамилия Set start)

                // *** End programmer edit section *** (Спикер.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Спикер.Фамилия Set end)

                // *** End programmer edit section *** (Спикер.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Спикер.Имя CustomAttributes)

        // *** End programmer edit section *** (Спикер.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Спикер.Имя Get start)

                // *** End programmer edit section *** (Спикер.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Спикер.Имя Get end)

                // *** End programmer edit section *** (Спикер.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спикер.Имя Set start)

                // *** End programmer edit section *** (Спикер.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Спикер.Имя Set end)

                // *** End programmer edit section *** (Спикер.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Спикер.Отчество CustomAttributes)

        // *** End programmer edit section *** (Спикер.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Спикер.Отчество Get start)

                // *** End programmer edit section *** (Спикер.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Спикер.Отчество Get end)

                // *** End programmer edit section *** (Спикер.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спикер.Отчество Set start)

                // *** End programmer edit section *** (Спикер.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Спикер.Отчество Set end)

                // *** End programmer edit section *** (Спикер.Отчество Set end)
            }
        }

        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Leechnost.FullName CustomAttributes)

        // *** End programmer edit section *** (Leechnost.FullName CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.SQLDataService), "@Фамилия@ || \' \' || @Имя@ || \' \' || COALESCE(@Отчество@, \'\')")]
        public virtual string FullName
        {
            get
            {
                // *** Start programmer edit section *** (Leechnost.FullName Get)
                return $"{this.Фамилия} {this.Имя} {this.Отчество}";
                // *** End programmer edit section *** (Leechnost.FullName Get)
            }
            set
            {
                // *** Start programmer edit section *** (Leechnost.FullName Set)

                // *** End programmer edit section *** (Leechnost.FullName Set)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпикерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпикерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпикерE", typeof(IIS.BookClub.Спикер));
                }
            }
            
            /// <summary>
            /// "СпикерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпикерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпикерL", typeof(IIS.BookClub.Спикер));
                }
            }
        }
    }
}
